# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/arm_design/arm_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design || ORIG_REF_NAME==arm_design} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_processing_system7_0_0/arm_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_processing_system7_0_0 || ORIG_REF_NAME==arm_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_dma_0_1/arm_design_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_dma_0_1 || ORIG_REF_NAME==arm_design_axi_dma_0_1} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_rst_ps7_0_100M_0/arm_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==arm_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_smc_2/arm_design_axi_smc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_smc_2 || ORIG_REF_NAME==arm_design_axi_smc_2} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_mem_intercon_2/arm_design_axi_mem_intercon_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_mem_intercon_2 || ORIG_REF_NAME==arm_design_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_gpio_0_1/arm_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_gpio_0_1 || ORIG_REF_NAME==arm_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_gpio_1_1/arm_design_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_gpio_1_1 || ORIG_REF_NAME==arm_design_axi_gpio_1_1} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_gpio_2_0/arm_design_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_gpio_2_0 || ORIG_REF_NAME==arm_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_mem_intercon_imp_s00_data_fifo_0 || ORIG_REF_NAME==arm_design_axi_mem_intercon_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/arm_design/ip/arm_design_axi_mem_intercon_imp_auto_pc_0/arm_design_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arm_design_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==arm_design_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.gen/sources_1/bd/arm_design/arm_design_ooc.xdc
