# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.srcs/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0.xci
# IP: The module: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.gen/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.gen/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.srcs/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0.xci
# IP: The module: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.gen/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/CK/Desktop/Vivado/ZC702_EVK/ZC702_EVK_Test.gen/sources_1/bd/arm_design/ip/arm_design_axi_mem_intercon_imp_s00_data_fifo_0/arm_design_axi_mem_intercon_imp_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_design_axi_mem_intercon_imp_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
